// Package chewsprite decodes NES CHR-ROM bit-plane sprite data into pixel
// grids. The data itself is in chr_data.go (generated by cmd/chew/chat/encode).
//
// Per pixel: color index in 0..3 (0 = transparent). The Palette table maps
// indices to RGBA colors from the source PNG.

package chewsprite

import "image/color"

// Frame is a 16x16 grid of palette indices.
type Frame [FramePixels][FramePixels]uint8

// DecodeFrameFrom returns the pixel grid for a given frame index out of any
// CHR table (e.g., the canonical CHEW CHR or GumCHR). totalFrames is used
// for bounds-checking. The decoder is sprite-agnostic: it reads the same
// 4-tile (TL/TR/BL/BR) bit-plane layout regardless of which sprite the CHR
// belongs to.
func DecodeFrameFrom(chr []byte, frame, totalFrames int) Frame {
	var grid Frame
	if frame < 0 || frame >= totalFrames {
		return grid
	}
	frameBase := frame * BytesPerFrame
	if frameBase+BytesPerFrame > len(chr) {
		return grid
	}
	tileOffsets := [TilesPerFrame][2]int{
		{0, 0}, {8, 0}, {0, 8}, {8, 8}, // TL, TR, BL, BR
	}
	for ti, tp := range tileOffsets {
		tileBase := frameBase + ti*BytesPerTile
		for row := 0; row < TilePixels; row++ {
			plane0 := chr[tileBase+row]
			plane1 := chr[tileBase+TilePixels+row]
			for col := 0; col < TilePixels; col++ {
				bit := byte(7 - col)
				p0 := (plane0 >> bit) & 1
				p1 := (plane1 >> bit) & 1
				idx := (p1 << 1) | p0
				grid[tp[1]+row][tp[0]+col] = idx
			}
		}
	}
	return grid
}

// DecodeFrame is the convenience wrapper for the canonical CHEW sprite.
func DecodeFrame(frame int) Frame {
	return DecodeFrameFrom(CHR[:], frame, NumFrames)
}

// DecodeGumFrame is the convenience wrapper for the GUM sprite.
func DecodeGumFrame(frame int) Frame {
	return DecodeFrameFrom(GumCHR[:], frame, GumNumFrames)
}

// FrameByLabel returns the index for a CHEW label, or -1 if unknown.
func FrameByLabel(label string) int {
	for i, l := range FrameLabels {
		if l == label {
			return i
		}
	}
	return -1
}

// GumFrameByLabel returns the index for a GUM label, or -1 if unknown.
func GumFrameByLabel(label string) int {
	for i, l := range GumFrameLabels {
		if l == label {
			return i
		}
	}
	return -1
}

// PaletteColor returns the RGBA for a CHEW palette index (0..3).
func PaletteColor(idx uint8) color.RGBA {
	if int(idx) >= len(Palette) {
		return Palette[0]
	}
	return Palette[idx]
}

// GumPaletteColor returns the RGBA for a GUM palette index (0..3).
func GumPaletteColor(idx uint8) color.RGBA {
	if int(idx) >= len(GumPalette) {
		return GumPalette[0]
	}
	return GumPalette[idx]
}
